name: dso-planner-fasthtml

services:
  app:
    # can set APP_IMAGE in .env to override the default image for local development or testing (e.g.V1.2.3)
    # to avoid local override build, use docker compose -f compose.yaml up -d --build
    image: ${APP_IMAGE:-ghcr.io/dmccallie/dso_planner_fasthtml:latest}
    container_name: dso-planner-fasthtml
    env_file:
      - .env
    ports:
      - "5010:5010"
    volumes:
      # lets make this named, so not exposed to host, since it makes local testing harder when created by container 
      - runtime-data:/app/runtime
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true

volumes:
  runtime-data: